name: Feature Request / Bug Report
description: Use this template to request a feature or report an issue.
title: "[Feature/Bug]: "
labels: ["feature", "bug", "needs-triage"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: "🔹 Description"
      description: "Provide a clear and concise description of the feature request or issue."
      placeholder: "Describe what needs to be done or what issue you encountered..."
    validations:
      required: true

  - type: input
    id: design-url
    attributes:
      label: "🎨 Design URL"
      description: "Link to Figma, Sketch, or any relevant design files (if applicable)."
      placeholder: "https://figma.com/design..."
  
  - type: textarea
    id: requirements
    attributes:
      label: "📌 Requirements"
      description: "List the requirements or expected behavior of this feature."
      placeholder: "- Should allow users to...\n- Must integrate with..."
  
  - type: textarea
    id: api-details
    attributes:
      label: "🔗 API Example (If Applicable)"
      description: "Provide an example of how the API should be used."
      placeholder: |
        **Example Request:**
        ```json
        GET /api/v1/users
        Headers: { Authorization: "Bearer token" }
        ```
        **Example Response:**
        ```json
        { "id": 1, "name": "John Doe" }
        ```